config/routes.rb
Arpabet::Application.routes.draw do
  
  resources :words, :only => [:index, :show]

  root :to => 'words#index'

end

app/models/search_pattern.rb
class SearchPattern
  
  attr_accessor :pattern

  def initialize(pattern)
    self.pattern = pattern.to_s
  end
  
  def to_query
    if pattern.starts_with? '*'
      "%" + clean_pattern
    elsif pattern.ends_with? '*'
      clean_pattern + "%"
    else
      "%#{clean_pattern}%"
    end
  end
  
  def clean_pattern
    pattern.sub("*", '')
  end
  
end

app/models/word.rb
class Word < ActiveRecord::Base
  
  validates_uniqueness_of :spelling
  validates_presence_of :spelling
  validates_presence_of :arpabet_transcription
  
  before_save :clean_up_spelling
  before_save :clean_up_arpabet_transcription
  
  def to_param
    self.spelling
  end

  # Find words with similarly ending arpabet transcriptions
  # Try for maximum match depth, decrementing it until something comes back
  #
  def rhymes
    depth = self.arpabet_transcription.split(' ').size
    results = []
    
    while depth > 1 && results.empty?
      depth -= 1
      pattern = "*" + self.arpabet_transcription.split(' ').reverse.take(depth).reverse.join(' ')
      results = Word.find_by_transcription_pattern(pattern)
    end
    
    results
  end

  private
  
  def clean_up_spelling
    spelling.gsub!(/\W/, ' ')
    spelling.strip!
    arpabet_transcription.chomp!
    spelling.downcase!
  end
  
  def clean_up_arpabet_transcription
    arpabet_transcription.strip!
    arpabet_transcription.chomp!
  end
  
  def self.find_rhymes_for(spelling)
    word = Word.find_by_spelling(spelling).rhymes.map(&:spelling)
  end
  
  def self.transcribe(spelling)
    word = Word.first(:conditions => {:spelling => spelling})
    word.arpabet_transcription unless word.blank?
  end
  
  def self.find_by_transcription_pattern(pattern)
    Word.where("arpabet_transcription LIKE ?", SearchPattern.new(pattern).to_query)
  end
  
  def self.import_cmudict
    cmudict_file = Rails.root.join("db/cmudict.0.7a.txt")
    File.open(cmudict_file).readlines.each do |line|
      word = Word.new
      word.spelling, word.arpabet_transcription = line.chomp.split('  ')
      word.save!
      puts word.to_yaml
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery
  
  after_filter :set_access_control_headers

  def set_access_control_headers 
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Request-Method'] = '*'
  end

end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  
  def index
  end
  
  def show
    @word = Word.find_by_spelling(params[:id])
    
    @per_page = (params[:limit] || 50).to_i
    
    @page = 1
    @page += (params[:skip].to_i/@per_page).to_i if params[:skip].present?
        
    @rhymes = @word.rhymes.paginate(:page => @page, :per_page => @per_page)

    if @word.blank?
      render :json => []
    elsif params[:delimited].present?
      render :text => @rhymes.map(&:spelling).join(';')
    elsif params[:full].present?
      render :json => @rhymes, :except => [:id, :created_at, :updated_at]
    else
      render :json => @rhymes.map(&:spelling)
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Arpabet</title>
  <%= csrf_meta_tags %>

<style type="text/css">
  
  body {
    font-family: "Helvetica Neue", Helvetica, Arial;
    padding: 20px;
  }
  
  p {
    width: 400px;
    font-weight: bold;
    font-size: 2em;
    color: #999;
  }
  
  p a {
    color: #0066CC;
  }
  
  p a.weak {
    color: #777;
    text-decoration: none;
  }

    
</style>  

</head>
<body>

<%= yield %>

</body>
</html>

app/views/words/index.html.haml
%p
  = link_to("I", "http://zeke.sikelianos.com", :class => 'weak')
  made a webservice for finding
  = link_to("rhymes", word_path('rhymes')) + "."

  You can also get the
  = link_to("Arpabet", "http://en.wikipedia.org/wiki/Arpabet", :class => 'weak')
  transcriptions if you 
  = link_to("fiddle", word_path('fiddle', :full => 1))
  with the params, you
  = link_to("monkey", word_path('monkey', :full => 1)) + '.'
  
  Source code is on 
  = link_to("github", "http://github.com/zeke/arpabet", :class => 'weak') + "."
  
  